apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selection-deployment
  namespace: dreem
  labels:
    app: node-selection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-selection
  template:
    metadata:
      labels:
        app: node-selection
    spec:
      containers:
      - name: node-selection
        image: dreem-selection:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: selection-service
  namespace: dreem
spec:
  selector:
    app: node-selection
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort