apiVersion: v1
kind: ConfigMap
metadata:
  name: selection-weights-scale-down
  namespace: dreem
data:
  energy: |
    PreferredNodeAffinity: "0.0089"
    PreferredPodAffinity: "0.0164"
    PreferredPodAntiAffinity: "0.0164"
    EnergyProfile: "0.6944"
    PowerCycles: "0.1689"
    NumberOfRunningPods: "0.0625"
    TopologySpread: "0.0625"
  neutral: |
    PreferredNodeAffinity: "0.0267"
    PreferredPodAffinity: "0.0492"
    PreferredPodAntiAffinity: "0.0492"
    EnergyProfile: "0.4167"
    PowerCycles: "0.0833"
    NumberOfRunningPods: "0.1874"
    TopologySpread: "0.1874"
  qos: |
    PreferredNodeAffinity: "0.0445"
    PreferredPodAffinity: "0.0821"
    PreferredPodAntiAffinity: "0.0821"
    EnergyProfile: "0.1389"
    PowerCycles: "0.0278"
    NumberOfRunningPods: "0.3124"
    TopologySpread: "0.3124"
