apiVersion: v1
kind: ConfigMap
metadata:
  name: selection-weights-scale-down
  namespace: dreem
data:
  energy: |
    PreferredNodeAffinity: "0.0053"
    PreferredPodAffinity: "0.0098"
    PreferredPodAntiAffinity: "0.0098"
    EnergyProfile: "0.7500"
    PowerCycles: "0.1500"
    NumberOfRunningPods: "0.0375"
    TopologySpread: "0.0375"
  neutral: |
    PreferredNodeAffinity: "0.0267"
    PreferredPodAffinity: "0.0492"
    PreferredPodAntiAffinity: "0.0492"
    EnergyProfile: "0.4167"
    PowerCycles: "0.0833"
    NumberOfRunningPods: "0.1874"
    TopologySpread: "0.1874"
  qos: |
    PreferredNodeAffinity: "0.0480"
    PreferredPodAffinity: "0.0886"
    PreferredPodAntiAffinity: "0.0886"
    EnergyProfile: "0.0833"
    PowerCycles: "0.0167"
    NumberOfRunningPods: "0.3373"
    TopologySpread: "0.3373"
