apiVersion: v1
kind: Secret
metadata:
  name: bmc-credentials-dreem-kind-worker 
  namespace: dreem
type: Opaque
stringData:
  username: test
  password: test
  bmc_address: test
  id: test
---

apiVersion: v1
kind: Secret
metadata:
  name: bmc-credentials-dreem-kind-worker2
  namespace: dreem
type: Opaque
stringData:
  username: test
  password: test
  bmc_address: test
  id: test
---