apiVersion: v1
kind: ConfigMap
metadata:
  name: forecast-parameters
  namespace: dreem
data:
  Past_time_window: "5" # in minutes, only for naive model. The LSTM has a fixed window of 120 min input and 60 min output
  Prometheus_time_window_prediction_in_minutes: "60"
  Thresholds_min: "40"
  Thresholds_max: "60"
  Forecast_period_in_minutes: "5"
  Prediction_model : "LSTM" # or naive
  Mean_time_to_boot: "1"
  Enabled: "true"
  Stabilization_cycles: "2" 
  
