# This rule is not used by the project operators itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over cluster.dreemk8s.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operators
    app.kubernetes.io/managed-by: kustomize
  name: clusterconfiguration-admin-role
rules:
- apiGroups:
  - cluster.dreemk8s
  resources:
  - clusterconfigurations
  verbs:
  - '*'
- apiGroups:
  - cluster.dreemk8s
  resources:
  - clusterconfigurations/status
  verbs:
  - get
