---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.dreemk8s
  resources:
  - clusterconfigurations
  - nodehandling
  - nodehandlings
  - nodeselecting
  - nodeselectings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.dreemk8s
  resources:
  - clusterconfigurations/finalizers
  - nodehandlings/finalizers
  - nodeselectings/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.dreemk8s
  resources:
  - clusterconfigurations/status
  - nodehandling/status
  - nodehandlings/status
  - nodeselecting/status
  - nodeselectings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  verbs:
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments/status
  verbs:
  - get
  - update
